language: generic
os: osx

install:
  # Download and install a minimal TeX Live, based on
  # https://github.com/latex3/latex3/blob/master/support/texlive.sh.
  - curl --location --remote-name http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
  - tar -xf install-tl-unx.tar.gz
  - cd install-tl-20*
  - echo -e "selected_scheme scheme-minimal\nTEXDIR /usr/local/texlive\noption_doc 0\noption_src 0" > texlive.profile
  - sudo ./install-tl -profile=texlive.profile
  - cd ..
  - PATH=$PATH:/usr/local/texlive/bin/x86_64-darwin
  - sudo tlmgr install
    datetime2
    datetime2-english
    etoolbox
    fontspec
    geometry
    gillius
    graphics
    hyphenex
    latex-bin
    libertinus-fonts
    luaotfload
    luatex85
    oberdiek
    pgf
    standalone
    tracklang
    varwidth
    xcolor
    xkeyval

before_script:
  - python --version

script:
  - ./init.py
  - for i in {1..2}; do lualatex -interaction=batchmode Letter.tex; done
